---
/offline_process/vo:
  ros__parameters:
    GNSSFGO:
      VehicleParameterPrefix: "Pohang_04"

    Pohang_04:   #04
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gnss", "lidar_front", "stereo_left", "stereo_right", "radar_low", "radar_high", "infrared"]
        imu:
          preRotate: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        reference:
          transFromBase: [ 0., 0., 0.]
          rotFromBase: [ 0., 0., 0. ]

        gnss:
          transFromBase: [ 5.2372448599999997, -0.026214491999999999, -1.924742161 ]
          rotFromBase: [ 0.99994147645540532, 0., 0., -0.010818672015746473, ]

        lidar_front:
          transFromBase: [ 5.2480345660000003, -0.064328983000000006, -0.38866764500000001  ]
          rotFromBase: [ -0.005370861000770469,  0.99826517514320456, -0.051288851007357569, 0.028412105004075816,]

        stereo_left:
          transFromBase: [ 4.9654692069314414, -0.37120398008980376, -1.7782174729825335 ]
          rotFromBase: [ 0.50265468456806928,  0.50706400510163241, 0.48825474310758404, 0.50182832586952864]

        stereo_right:
          transFromBase: [ 5.0569108031647287, 0.46791197097247561, -1.7634434537597872 ]
          rotFromBase: [0.5063821483779124,  0.50177257555434274, 0.4895244000297953, 0.50216258721772566 ]

        radar_low:
          transFromBase: [ -1.3001443918059703, 0.10347236997369438, -1.7156965094893029 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        radar_high:
          transFromBase: [  -1.2727583429023159, 0.1150319720751336, -2.4150650665578004]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        infrared:
          transFromBase: [ 4.9656355422084015, -0.3696776050497983, -1.7781905990206788 ]
          rotFromBase: [ 0.49892324034193403,  0.50684484810756714, 0.49746046286089479, 0.49670613856056434 ]

    Pohang00:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gnss", "lidar_front", "stereo_left", "stereo_right", "radar_low", "radar_high", "infrared"]
        imu:
          preRotate: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        reference:
          transFromBase: [ 0., 0., 0. ]
          rotFromBase: [ 0., 0., 0. ]

        gnss:
          transFromBase: [ 5.2372448599999997, -0.026214491999999999, -1.924742161 ]
          rotFromBase: [ 0.99994147645540532, 0., 0., -0.010818672015746473, ]

        lidar_front:
          transFromBase: [ 5.2480345660000003, -0.064328983000000006, -0.38866764500000001 ]
          rotFromBase: [ -0.005370861000770469,  0.99826517514320456, -0.051288851007357569, 0.028412105004075816, ]

        stereo_left:
          transFromBase: [ 5.0362549728344614, -0.44101021275849878, -1.771000242852925  ]
          rotFromBase: [ 0.4994824732081517,  0.50451874772890937, 0.49271166335600353, 0.50320304941532457, ]

        stereo_right:
          transFromBase: [ 5.0100574394498949, 0.40231815989499159, -1.7616651319571297 ]
          rotFromBase: [ 0.50391530412008612,  0.49957151499897112, 0.49321077340205338, 0.50323036541463029, ]

        radar_low:
          transFromBase: [ -1.3001443918059703, 0.10347236997369438, -1.7156965094893029 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        radar_high:
          transFromBase: [ -1.2727583429023159, 0.1150319720751336, -2.4150650665578004 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        infrared:
          transFromBase: [ 5.0327972904958269, -0.32970348745214439, -1.7697681477237637 ]
          rotFromBase: [ 0.49827309320382601,  0.50627112697925625, 0.49783276983638214, 0.49757009943653197 ]

    Pohang01:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gnss", "lidar_front", "stereo_left", "stereo_right", "radar_low", "radar_high", "infrared" ]
        imu:
          preRotate: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        reference:
          transFromBase: [ 0., 0., 0. ]
          rotFromBase: [ 0., 0., 0. ]

        gnss:
          transFromBase: [ 5.2372448599999997, -0.026214491999999999, -1.924742161 ]
          rotFromBase: [ 0.99994147645540532, 0., 0., -0.010818672015746473, ]

        lidar_front:
          transFromBase: [ 5.2480345660000003, -0.064328983000000006, -0.38866764500000001 ]
          rotFromBase: [ -0.005370861000770469,  0.99826517514320456, -0.051288851007357569, 0.028412105004075816, ]

        stereo_left:
          transFromBase: [ 5.014338433966488, -0.45844815534155892, -1.7715306793983654 ]
          rotFromBase: [ 0.4963617563165641,  0.5066540684114077, 0.49331742131926709, 0.50355196718056139, ]

        stereo_right:
          transFromBase: [ 5.0232126013345093, 0.35153206689707928, -1.7640839464868543 ]
          rotFromBase: [ 0.50103890326100342, 0.50083478110859303, 0.49440000252868271, 0.50367963722048281, ]

        radar_low:
          transFromBase: [ -1.3001443918059703, 0.10347236997369438, -1.7156965094893029 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        radar_high:
          transFromBase: [ -1.2727583429023159, 0.1150319720751336, -2.4150650665578004 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        infrared:
          transFromBase: [ 5.0165908324673119, -0.25286282607489252, -1.7696405846376906 ]
          rotFromBase: [ 0.49734814885778067, 0.50833540871065142, 0.49694472565617004, 0.4972784639628261  ]

    Pohang02:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gnss", "lidar_front", "stereo_left", "stereo_right", "radar_low", "radar_high", "infrared" ]
        imu:
          preRotate: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        reference:
          transFromBase: [ 0., 0., 0. ]
          rotFromBase: [ 0., 0., 0. ]

        gnss:
          transFromBase: [ 5.2372448599999997, -0.026214491999999999, -1.924742161 ]
          rotFromBase: [ 0.99994147645540532, 0., 0., -0.010818672015746473, ]

        lidar_front:
          transFromBase: [ 5.2480345660000003, -0.064328983000000006, -0.38866764500000001 ]
          rotFromBase: [ -0.005370861000770469,  0.99826517514320456, -0.051288851007357569, 0.028412105004075816, ]

        stereo_left:
          transFromBase: [ 5.0061999313092196, -0.48594401658505532, -1.7771777800930975  ]
          rotFromBase: [ 0.49929116480085178, 0.50548999285425522, 0.49137354891392726, 0.50372634962223828 ]

        stereo_right:
          transFromBase: [ 5.0407482027616393, 0.37492284501189382, -1.7612181783160448 ]
          rotFromBase: [ 0.50385425636352121, 0.50302710092268732, 0.49163446276494682, 0.50138825186027403 ]

        radar_low:
          transFromBase: [ -1.3001443918059703, 0.10347236997369438, -1.7156965094893029 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        radar_high:
          transFromBase: [ -1.2727583429023159, 0.1150319720751336, -2.4150650665578004 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        infrared:
          transFromBase: [ 5.01183055614728, -0.34564125171034188, -1.7745767082091497 ]
          rotFromBase: [ 0.49876431721708536, 0.50612878013881224, 0.49789106587832738, 0.49716425887699961 ]

    Pohang03:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gnss", "lidar_front", "stereo_left", "stereo_right", "radar_low", "radar_high", "infrared" ]
        imu:
          preRotate: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        reference:
          transFromBase: [ 0., 0., 0. ]
          rotFromBase: [ 0., 0., 0. ]

        gnss:
          transFromBase: [ 5.2372448599999997, -0.026214491999999999, -1.924742161 ]
          rotFromBase: [ 0.99994147645540532, 0., 0., -0.010818672015746473, ]

        lidar_front:
          transFromBase: [ 5.2480345660000003, -0.064328983000000006, -0.38866764500000001 ]
          rotFromBase: [ -0.005370861000770469,  0.99826517514320456, -0.051288851007357569, 0.028412105004075816, ]

        stereo_left:
          transFromBase: [ 4.9941992668526316, -0.46411534393110193, -1.7755366604022422 ]
          rotFromBase: [ 0.49958070775643082, 0.50423406783436975, 0.49090682181680906, 0.50515107994193953 ]

        stereo_right:
          transFromBase: [ 5.0401118098893294, 0.39550070252893338, -1.7445980987664604 ]
          rotFromBase: [ 0.50356768991134049, 0.49921501001607455, 0.49249535175063847, 0.50463083928355135]

        radar_low:
          transFromBase: [ -1.3001443918059703, 0.10347236997369438, -1.7156965094893029 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        radar_high:
          transFromBase: [ -1.2727583429023159, 0.1150319720751336, -2.4150650665578004 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        infrared:
          transFromBase: [ 5.0017442085657979, -0.3228521471166283, -1.7704524370706887 ]
          rotFromBase: [ 0.49787358829428341, 0.50371770365288826, 0.49971145461719157, 0.49867707710501963 ]

    Pohang05:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gnss", "lidar_front", "stereo_left", "stereo_right", "radar_low", "radar_high", "infrared" ]
        imu:
          preRotate: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        reference:
          transFromBase: [ 0., 0., 0. ]
          rotFromBase: [ 0., 0., 0. ]

        gnss:
          transFromBase: [ 5.2372448599999997, -0.026214491999999999, -1.924742161 ]
          rotFromBase: [ 0.99994147645540532, 0., 0., -0.010818672015746473, ]

        lidar_front:
          transFromBase: [ 5.2480345660000003, -0.064328983000000006, -0.38866764500000001 ]
          rotFromBase: [ -0.005370861000770469,  0.99826517514320456, -0.051288851007357569, 0.028412105004075816, ]

        stereo_left:
          transFromBase: [ 4.9502099544621085, -0.53684498350199261, -1.775100991864321  ]
          rotFromBase: [ 0.49990064099812886, 0.50507632283800241, 0.49242019912003077, 0.50251328811951956 ]

        stereo_right:
          transFromBase: [ 5.0389273710730773, 0.2881373786362002, -1.7641559411220706 ]
          rotFromBase: [ 0.50378588015645931, 0.49974464203010444, 0.49319700790427379, 0.50320154124511207 ]

        radar_low:
          transFromBase: [ -1.3001443918059703, 0.10347236997369438, -1.7156965094893029 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        radar_high:
          transFromBase: [ -1.2727583429023159, 0.1150319720751336, -2.4150650665578004 ]
          rotFromBase: [ -0.0087789409747089601,  0.99968042273937541, -0.0024609087130740472, 0.02357809397072758 ]

        infrared:
          transFromBase: [ 4.9712479328833581, -0.34121303885007787, -1.7725055405924961 ]
          rotFromBase: [ 0.49860650028039394, 0.50696459505785452, 0.49753525845135588, 0.49682705626173967 ]

    Boreas:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gps", "lidar", ]
        imu:
          preRotate: [ 0., 1., 0., 1., 0., 0., 0., 0., -1. ]

        reference:
          transFromBase: [ 0., 0., 0. ]
          rotFromBase: [ 0., 1., 0., 1., 0., 0., 0., 0., -1. ]

        gps:
          transFromBase: [ 0., 0., 0. ]
          rotFromBase: [ 0., 1., 0., 1., 0., 0., 0., 0., -1. ]

        lidar:
          transFromBase: [ -0.0249, 0.013439780101180,  -0.316013753414154 ]
          rotFromBase: [ 0.707106781186548,  0.707106781186548,  0.,
                          0.707106781186548, -0.707106781186548,  0.,
                          0.,  0., -1.0 ]

    KITTI:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gps", "lidar", ]
        imu:
          preRotate: [ 0., 0., 0. ]

        reference:
          transFromBase: [ -0.11, -0.49, -0.2085 ]
          rotFromBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        gps:
          transFromBase: [ -0.11, -0.49, -0.2085 ]
          rotFromBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        lidar:
          transFromBase: [ 0., 0., -0.04 ]
          rotFromBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

    DEloco:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "novatel_ant_main", "ublox_ant_main", "vlp16", "correvit" ]
        imu:
          preRotate: [ 0., 0., 0. ]

        reference:
          transFromBase: [ -0.11, -0.49, -0.2085 ]
          rotFromBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        novatel_ant_main:
          transFromBase: [ -0.11, -0.49, -0.2085 ]
          rotFromBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        ublox_ant_main:
          transFromBase: [ 0., 0., -0.04 ]
          rotFromBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        vlp16:
          transFromBase: [ 0.301411, 0., 0.0596 ]
          rotFromBase: [ 1., 0., 0., 0., -1., 0., 0., 0., -1. ]

        correvit:
          transFromBase: [ -1.78, 0., 1.2 ]
          rotFromBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]